// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conn.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	conn.proto

It has these top-level messages:
	Conn_ToS
	Conn_ToC
*/
package protocol

import proto "Golang-OnlineChatRoom/ProtobufChatRoom/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Conn_ToS struct {
	Nickname         *string `protobuf:"bytes,1,req,name=nickname" json:"nickname,omitempty"`
	Msg              *string `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Conn_ToS) Reset()                    { *m = Conn_ToS{} }
func (m *Conn_ToS) String() string            { return proto.CompactTextString(m) }
func (*Conn_ToS) ProtoMessage()               {}
func (*Conn_ToS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Conn_ToS) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *Conn_ToS) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type Conn_ToC struct {
	Nickname         *string `protobuf:"bytes,1,req,name=nickname" json:"nickname,omitempty"`
	Msg              *string `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Conn_ToC) Reset()                    { *m = Conn_ToC{} }
func (m *Conn_ToC) String() string            { return proto.CompactTextString(m) }
func (*Conn_ToC) ProtoMessage()               {}
func (*Conn_ToC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Conn_ToC) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *Conn_ToC) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Conn_ToS)(nil), "protocol.conn_ToS")
	proto.RegisterType((*Conn_ToC)(nil), "protocol.conn_ToC")
}

func init() { proto.RegisterFile("conn.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0xcf, 0xcb,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x16, 0x5c,
	0x1c, 0x20, 0xf1, 0xf8, 0x90, 0xfc, 0x60, 0x21, 0x29, 0x2e, 0x8e, 0xbc, 0xcc, 0xe4, 0xec, 0xbc,
	0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x26, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x80, 0x8b, 0x39,
	0xb7, 0x38, 0x5d, 0x82, 0x09, 0x2c, 0x0c, 0x62, 0x22, 0xe9, 0x74, 0x26, 0x4d, 0x27, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x33, 0xfa, 0x35, 0x53, 0x8a, 0x00, 0x00, 0x00,
}
